image: "python:3.7.4"

before_script:
  - bash scripts/prepare_gitlab_ci.sh
  - source /root/.bashrc
  - nvm use node
  - make setup-node
  - pip3 install -r requirements.txt

services:
  - name: mdillon/postgis
    alias: postgis

variables:
  POSTGRES_DB: bike_parking_toronto
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"

test:
  stage: test
  script:
  - source test/useci
  - make test
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - htmlcov/
  only:
    - master
    - merge_requests

pages:
  stage: deploy
  needs:
    - test
  script:
    - mkdir -p public/
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
    - merge_requests

deploy-staging:
  stage: deploy
  type: deploy
  needs:
    - test
  script: make deploy-staging
  only:
    - merge_requests

deploy-production:
  stage: deploy
  type: deploy
  needs:
    - test
  script: make deploy-prod
  only:
  - master
  - tags
