# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ip', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
