# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-22 00:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentrelineIntersectionWgs84',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('int_id', models.BigIntegerField(blank=True, null=True)),
                ('elev_id', models.BigIntegerField(blank=True, null=True)),
                ('intersec5', models.CharField(blank=True, max_length=250, null=True)),
                ('classifi6', models.CharField(blank=True, max_length=5, null=True)),
                ('classifi7', models.CharField(blank=True, max_length=80, null=True)),
                ('num_elev', models.SmallIntegerField(blank=True, null=True)),
                ('elevatio9', models.IntegerField(blank=True, null=True)),
                ('elevatio10', models.CharField(blank=True, max_length=80, null=True)),
                ('elev_level', models.SmallIntegerField(blank=True, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('elevatio13', models.CharField(blank=True, max_length=6, null=True)),
                ('height_r14', models.FloatField(blank=True, null=True)),
                ('height_r15', models.CharField(blank=True, max_length=6, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('objectid', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'centreline_intersection_wgs84',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closest', models.IntegerField(blank=True, default=1)),
                ('major', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceIP', models.GenericIPAddressField()),
                ('timeOf', models.DateTimeField(auto_now_add=True)),
                ('distance', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('survey', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('comments', models.TextField(default=None, null=True)),
                ('photo_uri', models.TextField(default=None, null=True)),
                ('photo_desc', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bicycleparking.SurveyAnswer'),
        ),
        migrations.AddField(
            model_name='event',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bicycleparking.Area'),
        ),
    ]
