# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection2d',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('int_id', models.BigIntegerField(blank=True, null=True)),
                ('intersec5', models.CharField(blank=True, max_length=250, null=True)),
                ('classifi6', models.CharField(blank=True, max_length=5, null=True)),
                ('classifi7', models.CharField(blank=True, max_length=80, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('objectid', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intersection2d',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='point_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
