# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0002_auto_20171129_0126'),
        ('bicycleparking', '0002_auto_20171129_0128'),
    ]

    operations = [
    ]
