# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0002_auto_20171129_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='point_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
