# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-13 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0003_merge_20171208_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_uri', models.TextField(default=None, null=True)),
                ('photo_desc', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='photo_desc',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='photo_uri',
        ),
        migrations.AddField(
            model_name='picture',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bicycleparking.SurveyAnswer'),
        ),
    ]
