# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0003_surveyanswer_point_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswer',
            name='point_timestamp',
        ),
    ]
