# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0004_auto_20170816_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='survey_answers',
            field=models.TextField(default=None),
        ),
    ]
