# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0004_auto_20171213_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='photo_uri',
            field=models.TextField(default=None, null=True),
        ),
    ]
