# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-23 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0005_surveyanswer_photo_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswer',
            name='photo_uri',
        ),
    ]
