# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0005_surveyanswer_survey_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='survey_answers',
            new_name='surveyanswers',
        ),
    ]
