# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-04 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0006_remove_surveyanswer_photo_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='photo', to='bicycleparking.SurveyAnswer'),
        ),
        migrations.AlterUniqueTogether(
            name='picture',
            unique_together=set([('answer', 'photo_uri')]),
        ),
    ]
