# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 21:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0006_auto_20170816_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswer',
            name='surveyanswers',
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='survey',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
    ]
