# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-16 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0007_auto_20180404_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOfApproval', models.DateTimeField(auto_now_add=True)),
                ('moderatorId', models.TextField(default=None, null=True)),
                ('approved', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bicycleparking.Event')),
            ],
        ),
    ]
