# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-26 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0007_auto_20170816_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswer',
            name='comments',
            field=models.TextField(default=None, null=True),
        ),
        # migrations.AlterField(
        #     model_name='surveyanswer',
        #     name='ip',
        #     field=models.GenericIPAddressField(),
        # ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='ip',
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='photo_desc',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='photo_uri',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='point_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
