# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-01 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0008_auto_20180416_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bicycleparking.SurveyAnswer'),
        ),
    ]
