# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 00:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0008_auto_20170826_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceIP', models.GenericIPAddressField()),
                ('postalCode', models.TextField(default=None, null=True)),
                ('timeOf', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='survey',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
