# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-03 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0009_auto_20180501_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default=None, null=True)),
            ],
        ),
    ]
