# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-02 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0009_auto_20180501_2356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='picture',
            unique_together=set([]),
        ),
    ]
