# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-24 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0011_auto_20180831_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.TextField()),
                ('timeOfApproval', models.DateTimeField(auto_now_add=True)),
                ('field', models.TextField()),
                ('edited', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bicycleparking.SurveyAnswer')),
            ],
        ),
    ]
