# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-15 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0012_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='area',
        ),
        migrations.RemoveField(
            model_name='event',
            name='distance',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
