# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-18 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0013_auto_20190415_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswer',
            name='comments',
        ),
    ]
